# Generated by Django 4.2.25 on 2025-10-05 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=300, unique=True)),
                ("mime_type", models.CharField(max_length=256, null=True)),
            ],
            options={
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vid_title", models.CharField(max_length=200, null=True)),
                ("location", models.CharField(max_length=300)),
                ("mime_type", models.CharField(max_length=256)),
                (
                    "vid_img",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="konektem.image",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "videos",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "service_img",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="konektem.image",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("news_title", models.TextField()),
                (
                    "news_img",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="konektem.image",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News",
            },
        ),
    ]
